### ISSUE TITLE
Connection establishing

### ISSUE THREAD

**Issue by ZedZipDev** [janniksam/SignalR.RequestResponse#2]
Hi ,thank you, it is great idea and implementation.

Is it possible to implement this kind of logic:

Client establishes connection to Server.
The Server uses this connection to send requests/responses to the Client? 

MfG,
Oleg.

**Comment by janniksam** [comment]
Basically you set up some request classes, which will be sent with SignalR to the Server and handled inside inside your RequestHandler. The RequestHandler will return the response. There are some opportunities for Logging and Dependency Injection already given.

The mechanic worked fine for a small game, I used to implement. It had 20 requests which were handled by the Server and sent back to the Client.

There are alot of things to write in a better way (code smells) and some todo's (SignalR's Client grouping is currently not supported), feel, free to have a look at the code and the examples included

**Comment by ZedZipDev** [comment]
Thnx, 
It is great, but I mean: how to establish connection Server->Client (not Client->Server) and after this work as usually, as you described above: Client sends->Request->Server and receives Responses from the Server

**Comment by janniksam** [comment]
I am not sure exactly what you are trying to do... 
Can you elaborate a little bit more, what exactly you're trying to accomplish?

**Comment by ZedZipDev** [comment]
Ok.
The usual way is:
1. Client connects to Server
2. Client sends requests and receives responses
3. Client receives callbacks from the Server

I'd like to change the p.1. Server connects to Client

It likes a reversing tunnel.

**Comment by janniksam** [comment]
Unfortunately this technique isn't supported by my SignalR extension.
